#!/usr/bin/env bash
# cloudshell_bootstrap.sh
#
# One-command bootstrap for the Operations Council in Google Cloud Shell.
# Replaces both .env setup and scripts/setup_env.sh from the local-dev version.
#
# What it does:
#   1. Detects PROJECT_ID from gcloud config (no manual export needed)
#   2. Creates a Python virtual environment in ~/.venv/operations-council
#   3. Installs all course dependencies
#   4. Generates a .env file from your gcloud config
#   5. Enables required APIs
#   6. Creates the service account, IAM bindings, Artifact Registry, BigQuery dataset
#   7. Loads the knowledge base into BigQuery
#
# Run from the repo root in Cloud Shell:
#   bash cloudshell_bootstrap.sh

set -euo pipefail

# ─── colors ───────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
RESET='\033[0m'

step() { echo -e "\n${BLUE}▶ $1${RESET}"; }
ok()   { echo -e "${GREEN}  ✓ $1${RESET}"; }
warn() { echo -e "${YELLOW}  ⚠ $1${RESET}"; }
err()  { echo -e "${RED}  ✗ $1${RESET}"; }

# ─── 1. Detect project ────────────────────────────────────────────────────────
step "Detecting Google Cloud project from gcloud config"

PROJECT_ID="${PROJECT_ID:-$(gcloud config get-value project 2>/dev/null || true)}"
if [[ -z "${PROJECT_ID}" || "${PROJECT_ID}" == "(unset)" ]]; then
  err "No project set. Run: gcloud config set project YOUR_PROJECT_ID"
  exit 1
fi
ok "PROJECT_ID = ${PROJECT_ID}"

REGION="${REGION:-us-central1}"
ok "REGION = ${REGION}"

PROJECT_NUMBER="$(gcloud projects describe "${PROJECT_ID}" --format='value(projectNumber)')"
ok "PROJECT_NUMBER = ${PROJECT_NUMBER}"

# ─── 2. Python venv ────────────────────────────────────────────────────────────
step "Setting up Python virtual environment"

VENV_DIR="${HOME}/.venv/operations-council"
PYTHON_BIN="$(command -v python3.12 || command -v python3.11 || command -v python3)"
ok "Using Python: ${PYTHON_BIN} ($($PYTHON_BIN --version))"

if [[ ! -d "${VENV_DIR}" ]]; then
  "${PYTHON_BIN}" -m venv "${VENV_DIR}"
  ok "Created venv at ${VENV_DIR}"
else
  ok "Venv already exists at ${VENV_DIR}"
fi

# shellcheck disable=SC1091
source "${VENV_DIR}/bin/activate"
ok "Activated venv (PATH: $(which python))"

step "Installing course dependencies"
pip install --quiet --upgrade pip
pip install --quiet -r requirements.txt
ok "Installed $(pip list --format=freeze | wc -l) packages"

# ─── 3. Write .env file ────────────────────────────────────────────────────────
step "Writing .env file"

SERVICE_ACCOUNT_NAME="operations-council-sa"
SA_EMAIL="${SERVICE_ACCOUNT_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
REPO_NAME="operations-council-repo"
BQ_DATASET="operations_council"

cat > .env <<EOF
# Generated by cloudshell_bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
PROJECT_ID="${PROJECT_ID}"
PROJECT_NUMBER="${PROJECT_NUMBER}"
REGION="${REGION}"

GOOGLE_GENAI_USE_VERTEXAI="TRUE"
GOOGLE_CLOUD_PROJECT="${PROJECT_ID}"
GOOGLE_CLOUD_LOCATION="${REGION}"

MODEL_PRO="gemini-2.0-pro"
MODEL_FLASH="gemini-2.0-flash"

BQ_DATASET="${BQ_DATASET}"
BQ_KB_TABLE="knowledge_base"

REPO_NAME="${REPO_NAME}"
SERVICE_ACCOUNT_NAME="${SA_EMAIL}"

# Cloud Shell specific
CLOUD_SHELL="TRUE"
EOF
ok ".env written ($(wc -l < .env) lines)"

# ─── 4. Enable APIs ────────────────────────────────────────────────────────────
step "Enabling required Google Cloud APIs (this can take 2–3 minutes)"

gcloud services enable \
  aiplatform.googleapis.com \
  artifactregistry.googleapis.com \
  bigquery.googleapis.com \
  cloudbuild.googleapis.com \
  cloudresourcemanager.googleapis.com \
  compute.googleapis.com \
  iam.googleapis.com \
  logging.googleapis.com \
  run.googleapis.com \
  secretmanager.googleapis.com \
  --project="${PROJECT_ID}" \
  --quiet
ok "All APIs enabled"

# ─── 5. Service account & IAM ──────────────────────────────────────────────────
step "Creating service account and granting roles"

if ! gcloud iam service-accounts describe "${SA_EMAIL}" --project="${PROJECT_ID}" &>/dev/null; then
  gcloud iam service-accounts create "${SERVICE_ACCOUNT_NAME}" \
    --display-name="Operations Council agent service account" \
    --project="${PROJECT_ID}" --quiet
  ok "Created service account ${SA_EMAIL}"
else
  ok "Service account already exists"
fi

# IAM propagation can lag service-account creation by a few seconds.
# Retry the first binding until it succeeds (or give up after ~60s).
bind_role() {
  local role="$1"
  local attempts=0
  local max=15
  until gcloud projects add-iam-policy-binding "${PROJECT_ID}" \
        --member="serviceAccount:${SA_EMAIL}" \
        --role="${role}" \
        --condition=None \
        --quiet >/dev/null 2>&1; do
    attempts=$((attempts + 1))
    if [[ ${attempts} -ge ${max} ]]; then
      err "Failed to bind ${role} after ${max} attempts"
      return 1
    fi
    sleep 4
  done
}

echo "  Waiting for IAM propagation and binding roles…"
for role in \
  roles/aiplatform.user \
  roles/artifactregistry.admin \
  roles/bigquery.dataEditor \
  roles/bigquery.jobUser \
  roles/cloudbuild.builds.editor \
  roles/iam.serviceAccountUser \
  roles/logging.logWriter \
  roles/logging.viewer \
  roles/run.admin \
  roles/secretmanager.secretAccessor \
  roles/storage.objectViewer; do
  bind_role "${role}"
done
ok "Granted 11 IAM roles to service account"

# ─── 6. Artifact Registry ──────────────────────────────────────────────────────
step "Creating Artifact Registry repository"

if ! gcloud artifacts repositories describe "${REPO_NAME}" \
       --location="${REGION}" --project="${PROJECT_ID}" &>/dev/null; then
  gcloud artifacts repositories create "${REPO_NAME}" \
    --repository-format=docker \
    --location="${REGION}" \
    --description="Operations Council agent images" \
    --project="${PROJECT_ID}" --quiet
  ok "Created repo ${REPO_NAME}"
else
  ok "Artifact Registry repo already exists"
fi

# ─── 7. BigQuery dataset ───────────────────────────────────────────────────────
step "Creating BigQuery dataset"

if ! bq --project_id="${PROJECT_ID}" show --dataset "${BQ_DATASET}" &>/dev/null; then
  bq --location="${REGION}" --project_id="${PROJECT_ID}" mk --dataset \
    --description="Knowledge base for the Operations Council" \
    "${PROJECT_ID}:${BQ_DATASET}"
  ok "Created BigQuery dataset ${BQ_DATASET}"
else
  ok "BigQuery dataset already exists"
fi

# ─── 8. Load knowledge base ────────────────────────────────────────────────────
step "Loading knowledge base into BigQuery"

set -a; source .env; set +a
if python scripts/load_knowledge_base.py 2>&1; then
  ok "Knowledge base loaded"
else
  warn "Knowledge base load failed — you can retry later with:"
  warn "  source ~/.venv/operations-council/bin/activate && python scripts/load_knowledge_base.py"
fi

# ─── done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${RESET}"
echo -e "${GREEN}  ✅  Operations Council bootstrap complete${RESET}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${RESET}"
echo ""
echo "To use the venv in a new shell tab:"
echo "  source ~/.venv/operations-council/bin/activate"
echo "  set -a && source .env && set +a"
echo ""
echo "Next steps:"
echo "  1. Verify environment:  python chapter_01_setup/verify_setup.py"
echo "  2. Try the prototype:   python chapter_02_agent_studio/single_agent_triage.py"
echo "  3. Run the Council:     python chapter_03_council/run_local.py"
echo ""
echo "Or open the interactive tutorial:"
echo "  cloudshell launch-tutorial cloudshell_tutorial.md"
echo ""
